import {
	FaUser,
	FaCalendar,
	FaDumbbell,
	FaTrash,
	FaEdit,
	FaCheck,
	FaPlus,
	FaMoneyBill,
	FaClock,
	FaIdCard,
	FaChalkboardTeacher,
	FaIdBadge,
	FaUserTie,
	FaChartLine,
	FaBarcode,
	FaPenSquare,
	FaShoppingBag,
	FaExternalLinkAlt,
} from 'react-icons/fa';

export const iconMap = {
	user: FaUser,
	calendar: FaCalendar,
	dumbbell: FaDumbbell,
	trash: FaTrash,
	edit: FaEdit,
	check: FaCheck,
	plus: FaPlus,
	money: FaMoneyBill,
	clock: FaClock,
	id: FaIdCard,
	teacher: FaChalkboardTeacher,
	empleado: FaIdBadge,
	corbata: FaUserTie,
	dashboard: FaChartLine,
	barcode: FaBarcode,
	addClass: FaPenSquare,
	bag: FaShoppingBag,
	external: FaExternalLinkAlt,
};
